### PR TITLE
fix: updated oauth hosts according latest battlenet api changes

### LINKED ISSUE #211: GetRealmsIndexAsync() failing for TW
basically I do have an client & secret for us endpoints.

using these api client id and secret values i can make calls to all realms except tw:

`                var result = await client.GetRealmsIndexAsync(@namespace);`

```
16:39:22 [INF] [RealmUpdater] querying realms of taiwan failed with System.Net.Http.HttpRequestException: Response code 401 (Unauthorized) does not indicate success. Request: https://tw.api.blizzard.com/data/wow/realm/index?namespace=dynamic-tw&locale=zh_TW
   at ArgentPonyWarcraftClient.WarcraftClient.GetAsync[T](String requestUri, String accessToken)
   at ArgentPonyWarcraftClient.WarcraftClient.GetAsync[T](String requestUri)
   at ArgentPonyWarcraftClient.WarcraftClient.GetRealmsIndexAsync(String namespace, Region region, Locale locale)
   at ArgentPonyWarcraftClient.WarcraftClient.GetRealmsIndexAsync(String namespace)
   at Wowtrack.Data.Updater.Jobs.Realm.RealmUpdater.GetRealmsForRegion(Region region, Locale locale) in C:\Coding\wowtrack.gg\core_dotnet\src\tools\updater\Jobs\Realm\RealmUpdater.cs:line 106..
```
 tw version fails:

`https://tw.api.blizzard.com/data/wow/realm/index?namespace=dynamic-tw&locale=zh_TW&access_token=TOKEN`

### PR DESCRIPTION
**Pull request by bonesoul**
closes #211.

### CODE REVIEW

**Comment by bonesoul** [comment]
hey, any updates on this?

**Review by danjagnow — APPROVED** [review]
Looks good!  This matches the docs at https://develop.battle.net/documentation/guides/using-oauth, as you indicated.

**Comment by danjagnow** [comment]
> hey, any updates on this?

My apologies for the delay.  Thanks for submitting this fix!

**Comment by bonesoul** [comment]
all good! thanks for the PR in.

**Pull request merged**
